import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "@/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const [queryClient]=useState(()=> new QueryClient())
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryProvider>

        {children}
        </ReactQueryProvider>
        
        </body>
    </html>
  );
}
